<?php
session_start();
if (empty($_SESSION['user_id'])) {
    header('Location: /nutriplan/index.php');
    exit;
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width,initial-scale=1.0">
  <title>Meal Planner — NutriPlan</title>
  <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,400;0,600;1,400&family=DM+Sans:wght@300;400;500;600&display=swap" rel="stylesheet">
  <link href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@3.0.0/dist/tabler-icons.min.css" rel="stylesheet">
  <link href="../assets/css/main.css?v=<?= time() ?>" rel="stylesheet">
  <link href="../assets/css/components.css?v=<?= time() ?>" rel="stylesheet">
  <link href="../assets/css/animations.css?v=<?= time() ?>" rel="stylesheet">
  <link href="../assets/css/pages/planner.css?v=<?= time() ?>" rel="stylesheet">
</head>
<body>

  <div class="progress-bar" id="pbar" style="width:60%"></div>

  <div class="app">
    <?php include '../includes/sidebar.php'; ?>

    <main class="main">
      <div class="topbar animate-in">
        <div>
          <div class="page-title">Weekly <span>Meal Plan</span></div>
          <div style="font-size:13px;color:var(--muted);margin-top:4px">May 26 – June 1, 2026</div>
        </div>
        <div class="topbar-right">
          <a href="/nutriplan/pages/grocery.php" class="btn btn-outline">📋 Grocery list</a>
          <button class="btn btn-lime" id="btn-generate-day">↻ Regenerate day</button>
          
          <div class="topbar-actions" style="display: flex; align-items: center; gap: 12px; margin-left: 12px; border-left: 1px solid var(--border); padding-left: 16px;">
            <a href="/nutriplan/pages/settings.php" class="topbar-action-btn" title="Settings" style="width: 38px; height: 38px; border-radius: 50%; background: var(--white); border: 1.5px solid var(--border); display: flex; align-items: center; justify-content: center; color: var(--muted); text-decoration: none; font-size: 18px; transition: var(--transition);" onmouseover="this.style.borderColor='var(--sage)'; this.style.color='var(--sage)';" onmouseout="this.style.borderColor='var(--border)'; this.style.color='var(--muted)';">
              <i class="ti ti-settings"></i>
            </a>
          </div>
        </div>
      </div>

      <!-- Calendar Day selector tabs -->
      <div class="calendar-tabs animate-in" id="calendar-days" style="display:flex; gap:8px; margin-bottom:20px;">
        <!-- Generated by JS -->
      </div>

      <!-- Daily totals progress bar strip -->
      <div style="display:flex;align-items:center;gap:10px;margin-bottom:18px" class="animate-in" style="animation-delay: 0.1s">
        <div style="flex:1;height:4px;border-radius:2px;background:var(--border);overflow:hidden">
          <div id="val-day-progress-bar" style="width:0%;height:100%;background:var(--sage);border-radius:2px;transition:width 1s;"></div>
        </div>
        <div style="font-size:12px;color:var(--muted)" id="val-day-progress-text">0 / 0 kcal today</div>
      </div>

      <!-- Planner Grid -->
      <div class="planner-grid animate-in" id="planner-meals" style="animation-delay: 0.15s">
        <!-- Generated by JS -->
      </div>

      <!-- Custom macro totals card matching planner mockup -->
      <div style="background:var(--white);border:1px solid var(--border);border-radius:var(--radius-sm);padding:14px 18px;margin-top:20px;display:flex;align-items:center;gap:14px;box-shadow:var(--shadow-sm);" class="animate-in" style="animation-delay: 0.2s">
        <div style="font-size:22px">📊</div>
        <div style="flex:1">
          <div style="font-size:13px;font-weight:600;margin-bottom:4px">Day Total Breakdown</div>
          <div style="display:flex;gap:14px;font-size:12px;color:var(--muted)"><span style="color:var(--coral)" id="lbl-total-prot">Protein 0g</span><span style="color:var(--amber)" id="lbl-total-carbs">Carbs 0g</span><span style="color:var(--sky)" id="lbl-total-fat">Fat 0g</span></div>
        </div>
        <div style="font-family:'Playfair Display',serif;font-size:22px;font-weight:600;color:var(--forest)" id="lbl-total-cal">0 kcal</div>
      </div>

      <!-- Food Swap Search Modal -->
      <div class="modal" id="swap-modal">
        <div class="modal-container" style="max-width: 650px;">
          <div class="modal-header">
            <h3 id="swap-modal-title">Search Food to Swap</h3>
            <button class="modal-close" onclick="closeSwapModal()">&times;</button>
          </div>
          <div class="modal-body">
            <div class="swap-search-bar" style="display:flex; gap:12px; margin-bottom:16px;">
              <input type="text" id="swap-search-input" class="form-input" placeholder="Search oatmeal, chicken breast, protein powder...">
              <button class="btn btn-primary" id="btn-swap-search">Search</button>
            </div>
            
            <div class="quick-chips-row" style="display:flex; gap:8px; flex-wrap:wrap; margin-bottom:20px;">
              <button class="quick-chip" data-query="egg">Egg</button>
              <button class="quick-chip" data-query="greek yogurt">Yogurt</button>
              <button class="quick-chip" data-query="chicken breast">Chicken</button>
              <button class="quick-chip" data-query="rice">Rice</button>
              <button class="quick-chip" data-query="salmon">Salmon</button>
              <button class="quick-chip" data-query="avocado">Avocado</button>
            </div>
            
            <div id="swap-results-grid" class="swap-results-list" style="display:flex; flex-direction:column; gap:12px; max-height:320px; overflow-y:auto;">
              <!-- Results rendered here -->
            </div>
          </div>
        </div>
      </div>

      <!-- Recipe modal steps overlay -->
      <div class="modal" id="recipe-detail-overlay">
        <div class="modal-container" style="max-width: 580px;">
          <div class="modal-header">
            <h3>Gourmet Recipe Preparation</h3>
            <button class="modal-close" onclick="closeRecipeOverlay()">&times;</button>
          </div>
          <div class="modal-body" id="recipe-overlay-body" style="padding: 24px;">
            <!-- Content loaded dynamically -->
          </div>
        </div>
      </div>

    </main>
  </div>

  <script src="../assets/js/api.js"></script>
  <script src="../assets/js/main.js"></script>
  <script src="../assets/js/planner.js"></script>
</body>
</html>
